export const USER_FETCH_DATA = "USER_FETCH_DATA";

export const UPLOAD_USER_FILE = "UPLOAD_USER_FILE";
export const UPLOAD_USER_REJECT = "UPLOAD_USER_REJECT";

export const SAVE_USER_FORM_DATA = "SAVE_USER_FORM_DATA";
export const SAVE_ERROR_USER_FORM_DATA = "SAVE_ERROR_USER_FORM_DATA";

export const UPLOAD_FILE = "UPLOAD_FILE";
export const UPLOAD_ERROR_FILE = "UPLOAD_ERROR_FILE";

export const USER_PERMISSION_DATA="USER_PERMISSION_DATA";
export const ERROR_USER_PERMISSION_FORM_DATA="ERROR_USER_PERMISSION_FORM_DATA";

export const USER_FETCH_DATA_BYID="USER_FETCH_DATA_BYID";
export const USER_FETCH_ALL_DATA_BYID="USER_FETCH_ALL_DATA_BYID";

export const USER_FILTER_FETCH_ALL_DATA="USER_FILTER_FETCH_ALL_DATA";
export const USER_FILTER_FETCH_DATA_BY_SELECTION="USER_FILTER_FETCH_DATA_BY_SELECTION";



